FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/node:22 AS build

WORKDIR /app

ARG BUILD_MODE=production

RUN corepack enable

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm exec vite build --mode ${BUILD_MODE}

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.14.1

COPY --from=build /app/dist /var/www
COPY nginx.conf /etc/nginx/nginx.conf
